codecov: 
  token: 159d02a7-4b52-435b-9d0b-236058e2939d
coverage:
  precision: 2
  round: down
  range: "1...100"
  status:
    patch:
      default:
        target: 70%
    project:
      default:
        target: 70%
        threshold: 5%
